### ISSUE TITLE
Will this work on Android?

### ISSUE THREAD

**Issue by jason-engage** [AlexDisler/ng-storekit#11]
Designed to work out of the box on both IOS and Android?

**Comment by ndcollins** [comment]
No it won't. It is hard-coded for iOS right now.

**Comment by jason-engage** [comment]
Wow, has anyone created an updated version that works with both? Its kinda crazy that its an IOS only wrapper for a library that works with both ios and android...

**Comment by ndcollins** [comment]
This library was written before they added the Android support. ng-storekit was last updated a year ago. The Android support was added to the plugin just last October.

**Comment by jason-engage** [comment]
Do you happen to have a compatible version? It seems to me that someone had to create one by now!

**Comment by ndcollins** [comment]
Not at this time, I've not been able to find one, either.

**Comment by jason-engage** [comment]
I'll try to do it tonight/tomorrow. It looks pretty straightforward. It's not a complicated wrapper.

**Comment by ndcollins** [comment]
Please share if you do. I'm kind of surprised this works since it is looking for a global storekit object and he plugin creates a global store object now.

Sent from my iPhone

On Aug 16, 2015, at 7:35 PM, jason-engage <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll try to do it tonight/tomorrow. It looks pretty straightforward. It's not a complicated wrapper.

-

**Comment by jason-engage** [comment]
Yea I've done a bit of research. I'm thinking that this plugin is a waste of time. We should be writing all the code using the store object, as its cross platform unlike storekit. See https://github.com/Fovea/cordova-plugin-purchase-demo/blob/master/www/js/index.js

**Comment by AlexDisler** [comment]
This library was written before the support for Android was added and the API was changed. Since then I just use cordova-plugin-purchase directly.
